# Generated by Django 2.1.7 on 2019-02-19 18:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='_original_wp_post',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
