# Generated by Django 3.2.9 on 2021-12-22 17:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_blogpostpage_body_add_code_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="_original_wp_post",
            # Make the field optional so we can create new Posts.
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
